services:
  nugs-dl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nugs-dl
    networks:
      - jakenet
    ports:
      - "6890:8080"
    volumes:
      # Mount downloads directory to persist downloaded files
      - /mnt/user/data/media/music:/music
      # Mount config directory to persist configuration (includes config.json)
      - /mnt/cache/appdata/nugs-dl/config:/app/config
      - /mnt/cache/appdata/nugs-dl/logs:/app/logs
    environment:
      # Set timezone
      - TZ=America/New_York
      - PUID=99
      - PGID=100
      # Optional: Set custom output path (defaults to /app/downloads)
      - NUGS_OUTPUT_PATH=/music
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  jakenet:
    external: true